<x-layouts.cms>

    <x-cms.seo-head :page="$page" />

    @php
        $gjsCss = data_get($page->blocks ?? [], 'css', '');
    @endphp

    <style>
        {{-- Component-level CSS generated by the visual editor's style manager.
             Output first so our base rules below can override when needed. --}}
        {!! $gjsCss !!}

        {{-- Base rules — placed AFTER $gjsCss so they win for layout/justify.
             Use !important on display to beat GrapesJS's ID-selector rules
             (specificity 1,0,0) which can set inline elements to inline-block,
             breaking the parent paragraph's text-align: justify. --}}
        .gjs-page-output p {
            text-align: justify;
            text-justify: inter-word;
        }

        .gjs-page-output p strong,
        .gjs-page-output p b,
        .gjs-page-output p em,
        .gjs-page-output p i,
        .gjs-page-output p u,
        .gjs-page-output p s,
        .gjs-page-output p span,
        .gjs-page-output p a,
        .gjs-page-output p mark,
        .gjs-page-output p abbr,
        .gjs-page-output p cite,
        .gjs-page-output p code {
            display: inline !important;
            text-align: inherit;
        }
    </style>

    {{-- GrapesJS pages own their full layout — no wrapper chrome needed --}}
    <div class="gjs-page-output">
        {!! $page->content !!}
    </div>

</x-layouts.cms>
