<?php

declare(strict_types=1);

/**
 * Extracted training schedule card data for /aapscm-training/ page.
 * Auto-generated by extract_aapscm_training.php - do not edit by hand.
 */

return array (
  0 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Procurement Professional (ACPP)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2023/11/2-2.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-procurement-professional-acpp/',
  ),
  2 => 
  array (
    'title' => 'Instructor-led virtual training - Chartered Procurement Manager (CPM)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2023/11/3-2.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-chartered-procurement-manager-acpm/',
  ),
  3 => 
  array (
    'title' => 'Instructor-led virtual training -American Certified Supply-Chain Professional (ACSCP)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2024/12/1-3.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-supplychain-professional-acscp/',
  ),
  4 => 
  array (
    'title' => 'Instructor-led virtual training - Chartered Supply Chain Manager (CSCM)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2024/12/2-3.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-chartered-supply-chain-manager-acscm/',
  ),
  5 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Tourism Professional (ACTP)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2023/11/Untitled-1.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-tourism-professional-actp/',
  ),
  6 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Digital Procurement & Analytics Professional (AC-DPA)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2023/11/6-2.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-digital-procurement-analytics-specialist-acdpas/',
  ),
  7 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified IT Procurement & Digital Transformation Professional (ACIPDT)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2023/11/7-2.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-it-procurement-digital-transformation-specialist-acipdts/',
  ),
  8 => 
  array (
    'title' => 'Instructor-led virtual training  - Chartered Supply Chain Technology Manager(CSCT)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2023/11/8-2.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-chartered-supply-chain-technology-managers-csct/',
  ),
  9 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Public Sector Procurement & Compliance Professional(AC-PSPC)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2023/11/9-2.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-public-sector-procurement-compliance-specialist-ac-pspcs/',
  ),
  10 => 
  array (
    'title' => 'Sustainable Green Procurement & Ethical Sourcing Professional (AC-SGPES)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2023/11/10-2.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-sustainable-procurement-ethical-sourcing-professional-acspesp/',
  ),
  11 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Procurement Risk Management Professional (AC-PRM)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2023/11/11-3.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-procurement-risk-management-specialist-ac-prms/',
  ),
  12 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Strategic Procurement & Supplier Relationship Professional (AC-SPR)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2023/11/12-2.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-strategic-procurement-supplier-relationship-specialist-ac-sprs/',
  ),
  13 => 
  array (
    'title' => 'Instructor-led virtual training - AAPSCM® Training Virtual - Chartered Supply Chain Artiﬁcial Intelligence Analyst (CSAI)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2023/11/13-2.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-chartered-supply-chain-arti%ef%ac%81cial-intelligence-analyst-csai/',
  ),
  14 => 
  array (
    'title' => 'Instructor-led virtual training - AAPSCM® Training Virtual - Chartered Healthcare Procurement Solutions Professional (CHPP)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2023/11/14-3.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-chartered-healthcare-procurement-solutions-professional-chpp/',
  ),
  15 => 
  array (
    'title' => 'Instructor-led virtual training - Chartered Strategic Procurement & Supplier Relationship Manager(CSP-SRM)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2023/11/15-2.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-chartered-strategic-procurement-supplier-relationship-specialist-csp-srm/',
  ),
  16 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Global Procurement & Cross-Border Supply Professional (AC-GPCS)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2024/11/new-one.png',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-global-procurement-cross-border-supply-specialist-ac-gpcss/',
  ),
  17 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Procurement Data Science & AI Professional (AC-PDS)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2024/11/close-up-business-woman-working-laptop_1089666-5771.png',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-procurement-data-science-ai-specialist-ac-pdss/',
  ),
  18 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Procurement Automation & RPA Professional(AC-PARP)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2024/11/student-6789.png',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-procurement-automation-rpa-specialist-ac-paras/',
  ),
  19 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Procurement Leadership & Change Management Professional(AC-PLCM)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2024/11/student-6543.png',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-procurement-leadership-change-management-specialist-acplcms/',
  ),
  20 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Supply Chain Cybersecurity Professional (AC-SCCP)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2024/11/What-is-Cyber-Security.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-supply-chain-cybersecurity-professional-ac-sccp/',
  ),
  21 => 
  array (
    'title' => 'Instructor-led virtual training - Chartered Advanced Supply Chain Cybersecurity Manager (CA-SCCM)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2024/11/4-Cybersecurity-in-the-Supply-Chain-1.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-chartered-advanced-supply-chain-cybersecurity-manager-ca-sccm/',
  ),
  22 => 
  array (
    'title' => 'Instructor-led virtual training - Chartered AI-Driven Sustainable Procurement Manager (CAI-SPM)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2024/11/QM0724-FEAT-Software-p1FT-GettyImages-1628291798-1024x576.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-chartered-ai-driven-sustainable-procurement-manager-ca-ispm/',
  ),
  23 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Blockchain for Supply Chain Professional (AC-BSCP)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2024/11/1695190541507.png',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-blockchain-for-supply-chain-professional-ac-bscp/',
  ),
  24 => 
  array (
    'title' => 'Instructor-led virtual training - Chartered Sustainable Supply Chain Manager (CSSCM)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2024/11/Untitled-1.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-chartered-sustainable-supply-chain-manager-csscm/',
  ),
  25 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Digital Supply Chain Integration Professional (AC-DSCI)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2024/11/Untitled-1-1.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-digital-supply-chain-integration-professional-ac-dscip/',
  ),
  26 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Global Supply Chain Risk and Resilience Professional(AC- GSRP)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2024/11/Risk-management-1.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-global-supply-chain-risk-and-resilience-professionalac-gsrp/',
  ),
  27 => 
  array (
    'title' => 'Instructor-led virtual training - Chartered Sustainable Culinary Tourism Manager (CSCTM)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2024/12/ehl-mjc-2-1024x682.webp',
    'href' => 'https://aapscm.org/aapscm-training-virtual-chartered-sustainable-culinary-tourism-manager-csctm/',
  ),
  28 => 
  array (
    'title' => 'Instructor-led virtual training - Chartered Tourism Manager (CTM)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-71.png',
    'href' => 'https://aapscm.org/aapscm-training-virtual-chartered-tourism-manager-ctm/',
  ),
  29 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified E-Commerce Strategy and Growth Professional (AC-ESGP)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-72.png',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-e-commerce-strategy-and-growth-professional-ac-esgp/',
  ),
  30 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Ethical Practices & Sustainable E-Commerce Professional (AC-SEEP)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-73.png',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-ethical-practices-amp-sustainable-e-commerce-professional-ac-seep/',
  ),
  31 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Digital Merchandising and User Experience Professional (AC-DMUX)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-74.png',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-digital-merchandising-and-user-experience-professional-ac-dmux/',
  ),
  32 => 
  array (
    'title' => 'Instructor-led virtual training - Chartered E-Commerce Data Analytics and AI Professional (CED-AI)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-21.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-chartered-e-commerce-data-analytics-and-ai-professional-ced-ai/',
  ),
  33 => 
  array (
    'title' => 'Instructor-led virtual training - Chartered Global Cross-Border E-Commerce Manager (CGCBE)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-22.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-chartered-global-cross-border-e-commerce-manager-cgcbe/',
  ),
  34 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Supply Chain Digital Transformation Manager (AC-SCDTM)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-23.jpg',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-supply-chain-digital-transformation-manager-ac-scdtm/',
  ),
  35 => 
  array (
    'title' => 'Instructor-led virtual training - American Certified Sustainable and Circular Supply Chain Professional (AC-CSCSP)®',
    'image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-77.png',
    'href' => 'https://aapscm.org/aapscm-training-virtual-american-certified-sustainable-and-circular-supply-chain-professional-ac-cscsp/',
  ),
);
