<?php

declare(strict_types=1);

/**
 * Extracted card data for /all-courses/ page.
 * Auto-generated by extract_all_courses.php � do not edit by hand.
 */

return [
    // ------------------------------------------------------------
    // Procurement Certifications
    // ------------------------------------------------------------
    [
        'section' => 'Procurement Certifications',
        'title'   => 'Chartered Procurement Manager (CPM)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-20.png',
        'href'    => 'https://aapscm.org/american-certified-procurement-manager-acpm/',
    ],
    [
        'section' => 'Procurement Certifications',
        'title'   => 'American Certified Procurement Professional (ACPP)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-21.png',
        'href'    => 'https://aapscm.org/acpp/',
    ],
    [
        'section' => 'Procurement Certifications',
        'title'   => 'American Certified Digital Procurement & Analytics Professional (AC-DPA)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-23.png',
        'href'    => 'https://aapscm.org/american-certified-digital-procurement-analytics-specialist/',
    ],
    [
        'section' => 'Procurement Certifications',
        'title'   => 'American Certified Procurement Risk Management Professional(AC-PRM)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-24.png',
        'href'    => 'https://aapscm.org/american-certified-procurement-risk-management-specialist/',
    ],
    [
        'section' => 'Procurement Certifications',
        'title'   => 'American Certified Strategic Procurement & Supplier Relationship Professional (AC-SPR)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-25.png',
        'href'    => 'https://aapscm.org/american-certified-strategic-procurement-supplier-relationship-specialist/',
    ],
    [
        'section' => 'Procurement Certifications',
        'title'   => 'Chartered Strategic Procurement & Supplier Relationship Manager(CSP-SRM)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-26.png',
        'href'    => 'https://aapscm.org/chartered-strategic-procurement-supplier-relationship-specialist/',
    ],
    [
        'section' => 'Procurement Certifications',
        'title'   => 'American Certified IT Procurement & Digital Transformation Professional(ACIPDT)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-27.png',
        'href'    => 'https://aapscm.org/american-certified-it-procurement-digital-transformation-specialist/',
    ],
    [
        'section' => 'Procurement Certifications',
        'title'   => 'American Certified Procurement Automation & RPA Professional(AC-PARP)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-28.png',
        'href'    => 'https://aapscm.org/american-certified-procurement-automation-rpa-specialist-ac-paras-2/',
    ],
    [
        'section' => 'Procurement Certifications',
        'title'   => 'American Certified Procurement Data Science & AI Professional(AC-PDS)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-29.png',
        'href'    => 'https://aapscm.org/american-certified-procurement-data-science-ai-specialist-ac-pdss/',
    ],
    [
        'section' => 'Procurement Certifications',
        'title'   => 'Chartered AI-Driven Sustainable Procurement Manager (CAI-SPM)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-30.png',
        'href'    => 'https://aapscm.org/chartered-ai-driven-sustainable-procurement-manager-ca-ispm/',
    ],
    [
        'section' => 'Procurement Certifications',
        'title'   => 'Chartered Healthcare Procurement Solutions Professional (CHPP)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-31.png',
        'href'    => 'https://aapscm.org/chartered-healthcare-procurement-solutions-professional-chpp/',
    ],
    [
        'section' => 'Procurement Certifications',
        'title'   => 'American Certified Public Sector Procurement & Compliance Professional(AC-PSPC)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-32.png',
        'href'    => 'https://aapscm.org/american-certified-public-sector-procurement-compliance-specialist/',
    ],
    [
        'section' => 'Procurement Certifications',
        'title'   => 'Sustainable Green Procurement & Ethical Sourcing Professional (AC-SGPES)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-33.png',
        'href'    => 'https://aapscm.org/american-certified-sustainable-procurement-ethical-sourcing-professional/',
    ],
    [
        'section' => 'Procurement Certifications',
        'title'   => 'American Certified Global Procurement & Cross-Border Supply Professional(AC-GPCS)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-35.png',
        'href'    => 'https://aapscm.org/american-certified-global-procurement-cross-border-supply-specialist-ac-gpcss/',
    ],
    [
        'section' => 'Procurement Certifications',
        'title'   => 'American Certified Procurement Leadership & Change Management Professional (AC-PLCM)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-36.png',
        'href'    => 'https://aapscm.org/american-certified-procurement-leadership-change-management-specialist/',
    ],
    // ------------------------------------------------------------
    // Supply Chain certifications
    // ------------------------------------------------------------
    [
        'section' => 'Supply Chain certifications',
        'title'   => 'Chartered Supply Chain Manager (CSCM)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-37.png',
        'href'    => 'https://aapscm.org/chartered-supply-chain-manager-acscm/',
    ],
    [
        'section' => 'Supply Chain certifications',
        'title'   => 'Chartered Supply Chain Technology Manager (CSCT)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-38.png',
        'href'    => 'https://aapscm.org/acsct/',
    ],
    [
        'section' => 'Supply Chain certifications',
        'title'   => 'American Certified Supply Chain Professional (ACSCP)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-39.png',
        'href'    => 'https://aapscm.org/the-american-certified-supply-chain-professional-acscp/',
    ],
    [
        'section' => 'Supply Chain certifications',
        'title'   => 'Chartered Supply Chain Artiﬁcial Intelligence Professional (CSAI)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-40.png',
        'href'    => 'https://aapscm.org/the-american-certified-supply-chain-artificial-intelligence-analyst-acsai/',
    ],
    [
        'section' => 'Supply Chain certifications',
        'title'   => 'American Certified Sustainable and Circular Supply Chain Professional (AC-CSCSP)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-41.png',
        'href'    => 'https://aapscm.org/american-certified-sustainable-and-circular-supply-chain-professional-ac-cscsp/',
    ],
    [
        'section' => 'Supply Chain certifications',
        'title'   => 'Chartered Sustainable Supply Chain Manager (CSSCM)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-42.png',
        'href'    => 'https://aapscm.org/chartered-sustainable-supply-chain-manager-csscm/',
    ],
    [
        'section' => 'Supply Chain certifications',
        'title'   => 'American Certified Blockchain for Supply Chain Professiona (AC-BSCP)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-43.png',
        'href'    => 'https://aapscm.org/american-certified-blockchain-for-supply-chain-professional-ac-bscp/',
    ],
    [
        'section' => 'Supply Chain certifications',
        'title'   => 'American Certified Supply Chain Cybersecurity Professional (AC-SCCP)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-44.png',
        'href'    => 'https://aapscm.org/american-certified-supply-chain-cybersecurity-professional-ac-sccp/',
    ],
    [
        'section' => 'Supply Chain certifications',
        'title'   => 'Chartered Advanced Supply Chain Cybersecurity Manager (CA-SCCM)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-45.png',
        'href'    => 'https://aapscm.org/chartered-advanced-supply-chain-cybersecurity-manager-ca-sccm/',
    ],
    [
        'section' => 'Supply Chain certifications',
        'title'   => 'American Certified Digital Supply Chain Integration Professional (AC-DSCI)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-46.png',
        'href'    => 'https://aapscm.org/american-certified-digital-supply-chain-integration-professional-ac-dscip/',
    ],
    [
        'section' => 'Supply Chain certifications',
        'title'   => 'American Certified Supply Chain Digital Transformation Manager (AC-SCDTM)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-47.png',
        'href'    => 'https://aapscm.org/american-certified-supply-chain-digital-transformation-manager-ac-scdtm/',
    ],
    [
        'section' => 'Supply Chain certifications',
        'title'   => 'American Certified Global Supply Chain Risk and Resilience Professional(AC- GSRP)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-48.png',
        'href'    => 'https://aapscm.org/american-certified-global-supply-chain-risk-and-resilience-professionalac-gsrp',
    ],
    // ------------------------------------------------------------
    // Tourism Management
    // ------------------------------------------------------------
    [
        'section' => 'Tourism Management',
        'title'   => 'American Certified Tourism Professional (ACTP)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-49.png',
        'href'    => 'https://aapscm.org/american-certified-tourism-professional/',
    ],
    [
        'section' => 'Tourism Management',
        'title'   => 'Chartered Tourism Manager (CTM)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-50.png',
        'href'    => 'https://aapscm.org/ctm/',
    ],
    [
        'section' => 'Tourism Management',
        'title'   => 'Chartered Sustainable Culinary Tourism Manager (CSCTM)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-51.png',
        'href'    => 'https://aapscm.org/chartered-sustainable-culinary-tourism-manager-csctm/',
    ],
    // ------------------------------------------------------------
    // E-Commerce Management & Administration
    // ------------------------------------------------------------
    [
        'section' => 'E-Commerce Management & Administration',
        'title'   => 'American Certified E-Commerce Strategy and Growth Professional (AC-ESGP)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-52.png',
        'href'    => 'https://aapscm.org/american-certified-e-commerce-strategy-and-growth-professional-ac-esgp/',
    ],
    [
        'section' => 'E-Commerce Management & Administration',
        'title'   => 'Chartered E-Commerce Data Analytics and AI Professional (CED-AI)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-53.png',
        'href'    => 'https://aapscm.org/chartered-e-commerce-data-analytics-and-ai-professional-ced-ai/',
    ],
    [
        'section' => 'E-Commerce Management & Administration',
        'title'   => 'Chartered Global Cross-Border E-Commerce Manager (CGCBE)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-54.png',
        'href'    => 'https://aapscm.org/chartered-global-cross-border-e-commerce-manager-cgcbe/',
    ],
    [
        'section' => 'E-Commerce Management & Administration',
        'title'   => 'American Certified Ethical Practices & Sustainable E-Commerce Professional (AC-SEEP)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-55.png',
        'href'    => 'https://aapscm.org/american-certified-ethical-practices-sustainable-e-commerce-professional-ac-seep/',
    ],
    [
        'section' => 'E-Commerce Management & Administration',
        'title'   => 'American Certified Digital Merchandising and User Experience Professional (AC-DMUX)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/03/1-56.png',
        'href'    => 'https://aapscm.org/american-certified-digital-merchandising-and-user-experience-professional-ac-dmux/',
    ],
    // ------------------------------------------------------------
    // AI courses
    // ------------------------------------------------------------
    [
        'section' => 'AI courses',
        'title'   => 'Chartered Supply Chain Artificial Intelligence Manager (CSAI-M®)',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/10/logo-Chartered-Supply-Chain-Artificial-Intelligence-Manager-CSAI-M®.png',
        'href'    => 'https://aapscm.org/chartered-supply-chain-artificial-intelligence-manager-csai-m/',
    ],
    [
        'section' => 'AI courses',
        'title'   => 'American Certified Supply Chain Artificial Intelligence (AI) Professional – AC-SCAI®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/10/american.png',
        'href'    => 'https://aapscm.org/american-certified-supply-chain-artificial-intelligence-ai-professional-ac-scai/',
    ],
    [
        'section' => 'AI courses',
        'title'   => 'American Certified AI Procurement Chatbot & Supplier Relations Professional (AC-AIPCSR)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/07/1-10.png',
        'href'    => 'https://aapscm.org/american-certified-ai-procurement-chatbot-amp-supplier-relations-professional-ac-aipcsr/',
    ],
    [
        'section' => 'AI courses',
        'title'   => 'American Certified AI Procurement Demand & Forecasting Analyst (AC-AIPDFA)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/07/1-9.png',
        'href'    => 'https://aapscm.org/american-certified-ai-procurement-demand-amp-forecasting-analyst-ac-aipdfa/',
    ],
    [
        'section' => 'AI courses',
        'title'   => 'American Certified AI & Blockchain Procurement Professional (AC-AIBPP)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/07/1-8.png',
        'href'    => 'https://aapscm.org/american-certified-ai-amp-blockchain-procurement-professional-ac-aibpp/',
    ],
    [
        'section' => 'AI courses',
        'title'   => 'American Certified AI Supply Chain Resilience & Crisis Manager (AC-AISCRC)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/07/1-7.png',
        'href'    => 'https://aapscm.org/american-certified-ai-supply-chain-resilience-amp-crisis-manager-ac-aiscrc/',
    ],
    [
        'section' => 'AI courses',
        'title'   => 'Chartered Supply Chain Artificial Intelligence (CSAI)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/07/1-6.png',
        'href'    => 'https://aapscm.org/chartered-supply-chain-artificial-intelligence-csai/',
    ],
    [
        'section' => 'AI courses',
        'title'   => 'Certified AI Procurement Fraud & Cybersecurity Manager (CAIPFCM)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/07/1-5.png',
        'href'    => 'https://aapscm.org/american-certified-ai-procurement-fraud-amp-cybersecurity-manager-caipfcm/',
    ],
    [
        'section' => 'AI courses',
        'title'   => 'Chartered AI Supplier Negotiation & Risk Manager (CAISNRM)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/07/1-4.png',
        'href'    => 'https://aapscm.org/chartered-ai-supplier-negotiation-risk-manager-caisnrm/',
    ],
    [
        'section' => 'AI courses',
        'title'   => 'Chartered Sustainable Procurement & ESG AI Manager (CSPEAI)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/07/1-3.png',
        'href'    => 'https://aapscm.org/chartered-sustainable-procurement-esg-ai-manager-cspeai/',
    ],
    [
        'section' => 'AI courses',
        'title'   => 'Certified AI & RPA Procurement Professional (CAIRPP)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/07/1-2.png',
        'href'    => 'https://aapscm.org/certified-ai-amp-rpa-procurement-professional-cairpp/',
    ],
    [
        'section' => 'AI courses',
        'title'   => 'Chartered AI Supply Chain Analyst (CAISCA)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/07/1-1.png',
        'href'    => 'https://aapscm.org/chartered-ai-supply-chain-analyst-caisca/',
    ],
    [
        'section' => 'AI courses',
        'title'   => 'Chartered AI Procurement Strategist (CAIPS)®',
        'image'   => 'https://aapscm.org/wp-content/uploads/2025/07/1.png',
        'href'    => 'https://aapscm.org/chartered-ai-procurement-strategist-caips/',
    ],
];
