<?php

// Auto-generated by extract_certifications_for_professionals.php
// Source: ../../../Live Pages HTML/certifications-for-professionals.html
// Do not hand-edit — re-run the extractor if the live page changes.

return array (
  0 =>
  array (
    'title' => 'Testing Overview',
    'desc' => 'Designed by industry experts, highly relevant in today’s supply chain marketplace',
    'href' => 'https://aapscm.org/my-account/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2023/09/image.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2023/09/image-6.png',
  ),
  1 =>
  array (
    'title' => 'American Certified Procurement Professional (ACPP)®',
    'desc' => 'American Certifed Procurement Professional (ACPP)® certification shows future employers that you have the …',
    'href' => 'https://aapscm.org/acpp/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2023/10/Untitled-design-3.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/12/3-2.png',
  ),
  2 =>
  array (
    'title' => 'Chartered Procurement Manager (CPM)®',
    'desc' => 'The American Certified Procurement Manager (CPM)® tests knowledge and skills of a procurement manager.',
    'href' => 'https://aapscm.org/american-certified-procurement-manager-acpm/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2023/12/1.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2023/12/CPM.png',
  ),
  3 =>
  array (
    'title' => 'American Certified Supply Chain Professional (ACSCP)®',
    'desc' => 'The American Certified Supply Chain Professional …',
    'href' => 'https://aapscm.org/the-american-certified-supply-chain-professional-acscp/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2023/10/Untitled-design-8.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/12/2-3.png',
  ),
  4 =>
  array (
    'title' => 'Chartered Supply Chain Manager (CSCM)®',
    'desc' => 'The American Certified Supply Chain Manager (CSCM®) certification shows future employers that you have the …',
    'href' => 'https://aapscm.org/chartered-supply-chain-manager-acscm/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2023/12/2.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2023/12/CSCM.png',
  ),
  5 =>
  array (
    'title' => 'Chartered Supply Chain Artiﬁcial Intelligence Professional (CSAI)®',
    'desc' => 'The CSAI® certification is internationally recognized and focuses on the examination of end-to-end (E2E) visibility in supply chains.',
    'href' => 'https://aapscm.org/the-american-certified-supply-chain-artificial-intelligence-analyst-acsai/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2023/11/111.jpg',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2023/12/CSAI.png',
  ),
  6 =>
  array (
    'title' => 'American Certified Digital Procurement & Analytics Professional (AC-DPA)®',
    'desc' => 'This program would focus on the intersection..',
    'href' => 'https://aapscm.org/american-certified-digital-procurement-analytics-specialist/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/12/1-5.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/1-17.png',
  ),
  7 =>
  array (
    'title' => 'Sustainable Green Procurement & Ethical Sourcing Professional (AC-SGPES)®',
    'desc' => 'With an increasing focus on sustainability, this program would educate professionals on green procurement practices, sourcing..',
    'href' => 'https://aapscm.org/american-certified-sustainable-procurement-ethical-sourcing-professional/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/12/1-39.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/2-4.png',
  ),
  8 =>
  array (
    'title' => 'American Certified Procurement Risk Management Professional(AC-PRM)®',
    'desc' => 'This program would specialize in identifying, assessing, and managing procurement risks, such as supply chain disruptions, geopolitical factors, and….',
    'href' => 'https://aapscm.org/american-certified-procurement-risk-management-specialist/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/12/2-1.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/4-2.png',
  ),
  9 =>
  array (
    'title' => 'American Certified Strategic Procurement & Supplier Relationship Professional (AC-SPR)®',
    'desc' => 'In today’s competitive landscape….',
    'href' => 'https://aapscm.org/american-certified-strategic-procurement-supplier-relationship-specialist/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/12/3-1.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/5-2.png',
  ),
  10 =>
  array (
    'title' => 'Chartered Strategic Procurement & Supplier Relationship Manager(CSP-SRM)®',
    'desc' => 'Strategic Procurement and Supplier Relationship Management (CSP-SRM) is a critical aspect of modern supply chain…',
    'href' => 'https://aapscm.org/chartered-strategic-procurement-supplier-relationship-specialist/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/11/8-2.jpg',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/8-2.png',
  ),
  11 =>
  array (
    'title' => 'American Certified IT Procurement & Digital Transformation Professional(ACIPDT)®',
    'desc' => 'As organizations continue to digitize, the..',
    'href' => 'https://aapscm.org/american-certified-it-procurement-digital-transformation-specialist/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/12/4-2.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/6-3.png',
  ),
  12 =>
  array (
    'title' => 'American Certified Public Sector Procurement & Compliance Professional(AC-PSPC)®',
    'desc' => 'Procurement in the public sector requires…',
    'href' => 'https://aapscm.org/american-certified-public-sector-procurement-compliance-specialist/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/12/5.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/7-2.png',
  ),
  13 =>
  array (
    'title' => 'American Certified Global Procurement & Cross-Border Supply Professional(AC-GPCS)®',
    'desc' => 'Global procurement introduces unique challenges and opportunities.',
    'href' => 'https://aapscm.org/american-certified-global-procurement-cross-border-supply-specialist-ac-gpcss/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/12/6.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/8-3.png',
  ),
  14 =>
  array (
    'title' => 'American Certified Procurement Data Science & AI Professional(AC-PDS)®',
    'desc' => 'The AC-PDS Certification is designed for procurement professionals who want to leverage advanced data science and AI..',
    'href' => 'https://aapscm.org/american-certified-procurement-data-science-ai-specialist-ac-pdss/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/12/7.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/9-1.png',
  ),
  15 =>
  array (
    'title' => 'American Certified Procurement Leadership & Change Management Professional (AC-PLCM)®',
    'desc' => 'Effective procurement requires not only..',
    'href' => 'https://aapscm.org/american-certified-procurement-leadership-change-management-specialist/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/12/8.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/11.png',
  ),
  16 =>
  array (
    'title' => 'American Certified Procurement Automation & RPA Professional(AC-PARP)®',
    'desc' => 'The AC-PARP Certification focuses on leveraging automation and RPA technologies to transform traditional procurement practices. It is designed ..',
    'href' => 'https://aapscm.org/american-certified-procurement-automation-rpa-specialist-ac-paras-2/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/12/9.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/13.png',
  ),
  17 =>
  array (
    'title' => 'American Certified Tourism Professional (ACTP)®',
    'desc' => 'Tourism is one of the world’s leading industries and a major economic development tool, and as such, security (crime and terrorism) has a major..',
    'href' => 'https://aapscm.org/american-certified-tourism-professional/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/07/11.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/12/1-8.png',
  ),
  18 =>
  array (
    'title' => 'Chartered Supply Chain Technology Manager (CSCT)®',
    'desc' => 'The CSCT® certification is highly sought-after and unique, catering to professionals and managers in both the procurement and supply chain industries.',
    'href' => 'https://aapscm.org/acsct/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2023/11/33.jpg',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2023/12/CSCT.png',
  ),
  19 =>
  array (
    'title' => 'Chartered Healthcare Procurement Solutions Professional (CHPP)®',
    'desc' => 'The CHPP® Certification is the foundation level for analysts or Professionals in medical.',
    'href' => 'https://aapscm.org/chartered-healthcare-procurement-solutions-professional-chpp/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2023/10/2222.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2023/12/CHPP.png',
  ),
  20 =>
  array (
    'title' => 'American Certified Supply Chain Cybersecurity Professional (AC-SCCP)®',
    'desc' => 'The Supply Chain Cybersecurity Professional Certification (AC-SCCP) is designed for professionals seeking practical, foundational….',
    'href' => 'https://aapscm.org/american-certified-supply-chain-cybersecurity-professional-ac-sccp/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/11/new-cousres1.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/1-19.png',
  ),
  21 =>
  array (
    'title' => 'Chartered Advanced Supply Chain Cybersecurity Manager (CA-SCCM)®',
    'desc' => 'The Advanced Supply Chain Cybersecurity Manager Certification (CA-SCCM) equips professionals with the expertise to protect ..',
    'href' => 'https://aapscm.org/chartered-advanced-supply-chain-cybersecurity-manager-ca-sccm/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/11/new-cousres2.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/2-5.png',
  ),
  22 =>
  array (
    'title' => 'Chartered AI-Driven Sustainable Procurement Manager (CAI-SPM)®',
    'desc' => 'The AI-Driven Sustainable Procurement Manager Certification (CAI-SPM) is designed to empower professionals to lead the future….',
    'href' => 'https://aapscm.org/chartered-ai-driven-sustainable-procurement-manager-ca-ispm/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/12/10.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/3-2.png',
  ),
  23 =>
  array (
    'title' => 'American Certified Blockchain for Supply Chain Professional ®',
    'desc' => 'The Blockchain for Supply Chain Professional Certification (AC-BSCP) is designed for individuals and organizations ..',
    'href' => 'https://aapscm.org/american-certified-blockchain-for-supply-chain-professional-ac-bscp/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/11/new-cousres4.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/4-3.png',
  ),
  24 =>
  array (
    'title' => 'Chartered Sustainable Supply Chain Manager (CSSCM)®',
    'desc' => 'The Sustainable Supply Chain Management Certification (CSSCM) empowers professionals to design and manage eco…',
    'href' => 'https://aapscm.org/chartered-sustainable-supply-chain-manager-csscm/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/11/new-cousres5.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/5-3.png',
  ),
  25 =>
  array (
    'title' => 'American Certified Digital Supply Chain Integration Professional (AC-DSCI)®',
    'desc' => 'The American CertifiedDigital Supply Chain Integration Professional Certification (AC-DSCI) equips professionals..',
    'href' => 'https://aapscm.org/american-certified-digital-supply-chain-integration-professional-ac-dscip/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/12/11.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/6-4.png',
  ),
  26 =>
  array (
    'title' => 'American Certified Global Supply Chain Risk and Resilience Professional(AC- GSRP)®',
    'desc' => 'The Global Supply Chain Risk and Resilience Professional….',
    'href' => 'https://aapscm.org/american-certified-global-supply-chain-risk-and-resilience-professionalac-gsrp/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/11/new-cousres7.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/11/7-3.png',
  ),
  27 =>
  array (
    'title' => 'Chartered Sustainable Culinary Tourism Manager (CSCTM®)',
    'desc' => 'Take your career in culinary tourism to the next level with the Chartered Sustainable Culinary Tourism Manager (CSCTM®) certification!',
    'href' => 'https://aapscm.org/chartered-sustainable-culinary-tourism-manager-csctm/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2024/12/1-9.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2024/12/badge.png',
  ),
  28 =>
  array (
    'title' => 'Chartered Tourism Manager (CTM)®',
    'desc' => 'Welcome to the Chartered Tourism Manager (CTM)® program, proudly offered by the ..',
    'href' => 'https://aapscm.org/ctm/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-45.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-46.png',
  ),
  29 =>
  array (
    'title' => 'American Certified E-Commerce Strategy and Growth Professional (AC-ESGP)®',
    'desc' => 'The American Certified E-Commerce Strategy and Growth Professional (AC-ESGP)® certification is a comprehensive program …',
    'href' => 'https://aapscm.org/american-certified-e-commerce-strategy-and-growth-professional-ac-esgp/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-47.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-48.png',
  ),
  30 =>
  array (
    'title' => 'American Certified Ethical Practices & Sustainable E-Commerce Professional (AC-SEEP)®',
    'desc' => 'The AC-SEEP® Certification is the industry-leading credential for professionals committed to building ethical, sustainable, and impactful…',
    'href' => 'https://aapscm.org/american-certified-ethical-practices-sustainable-e-commerce-professional-ac-seep/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-54.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-53.png',
  ),
  31 =>
  array (
    'title' => 'American Certified Digital Merchandising and User Experience Professional (AC-DMUX)®',
    'desc' => 'The AC-DMUX® Certification is a premier credential designed to empower professionals with advanced Digital merchandising…',
    'href' => 'https://aapscm.org/american-certified-digital-merchandising-and-user-experience-professional-ac-dmux/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-55.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-56.png',
  ),
  32 =>
  array (
    'title' => 'Chartered E-Commerce Data Analytics and AI Professional (CED-AI)®',
    'desc' => 'The Chartered E-Commerce Data Analytics and AI Professional (CED-AI)® certification is a cutting-edge credential designed. …',
    'href' => 'https://aapscm.org/chartered-e-commerce-data-analytics-and-ai-professional-ced-ai/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-50.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-49.png',
  ),
  33 =>
  array (
    'title' => 'Chartered Global Cross-Border E-Commerce Manager (CGCBE)®',
    'desc' => 'The Chartered Global Cross-Border E-Commerce Manager (CGCBE)® certification is a world-class credential designed…',
    'href' => 'https://aapscm.org/chartered-global-cross-border-e-commerce-manager-cgcbe/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-51.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-52.png',
  ),
  34 =>
  array (
    'title' => 'American Certified Sustainable and Circular Supply Chain Professional (AC-CSCSP)®',
    'desc' => 'The American Certified Sustainable and Circular Supply Chain Professional (AC-CSCSP)® certification is a pioneering program created by the….',
    'href' => 'https://aapscm.org/american-certified-sustainable-and-circular-supply-chain-professional-ac-cscsp/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-39.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-40.png',
  ),
  35 =>
  array (
    'title' => 'American Certified Supply Chain Digital Transformation Manager (AC-SCDTM)®',
    'desc' => 'The AmericanCertified Supply Chain Digital Transformation Manager (AC-SCDTM)® certification is a groundbreaking program designed by th……',
    'href' => 'https://aapscm.org/american-certified-supply-chain-digital-transformation-manager-ac-scdtm/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-41.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/01/1-42.png',
  ),
  36 =>
  array (
    'title' => 'Chartered AI Procurement Strategist (CAIPS)®',
    'desc' => 'Focus: AI-driven procurement strategy, automation, and spend analysis.',
    'href' => 'https://aapscm.org/chartered-ai-procurement-strategist-caips/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/02/Untitled-design-3.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-8.png',
  ),
  37 =>
  array (
    'title' => 'Chartered AI Supply Chain Analyst (CAISCA)®',
    'desc' => 'Focus: Predictive analytics, demand forecasting, and risk mitigation.',
    'href' => 'https://aapscm.org/chartered-ai-supply-chain-analyst-caisca/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/02/2-4.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-9.png',
  ),
  38 =>
  array (
    'title' => 'Certified AI & RPA Procurement Professional (CAIRPP)®',
    'desc' => 'Focus: Robotic Process Automation (RPA) in procurement operations.',
    'href' => 'https://aapscm.org/certified-ai-amp-rpa-procurement-professional-cairpp/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-104.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-10-1.png',
  ),
  39 =>
  array (
    'title' => 'Chartered Sustainable Procurement & ESG AI Manager (CSPEAI)®',
    'desc' => 'Focus: AI-driven sustainability tracking, ethical sourcing, and ESG compliance.',
    'href' => 'https://aapscm.org/chartered-sustainable-procurement-esg-ai-manager-cspeai/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/02/4-4.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-11.png',
  ),
  40 =>
  array (
    'title' => 'Chartered AI Supplier Negotiation & Risk Manager (CAISNRM)®',
    'desc' => 'Focus: AI-enhanced supplier risk assessment and contract negotiation.',
    'href' => 'https://aapscm.org/chartered-ai-supplier-negotiation-risk-manager-caisnrm/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/02/5-4.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-12.png',
  ),
  41 =>
  array (
    'title' => 'Certified AI Procurement Fraud & Cybersecurity Manager (CAIPFCM)®',
    'desc' => 'Focus: AI-driven fraud detection, procurement cybersecurity, and compliance automation.',
    'href' => 'https://aapscm.org/american-certified-ai-procurement-fraud-amp-cybersecurity-manager-caipfcm/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-75.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-14.png',
  ),
  42 =>
  array (
    'title' => 'Chartered Supply Chain Artificial Intelligence (CSAI)®',
    'desc' => 'Focus: AI & ML in Supply Chain Optimization Automation & Robotics in Logistics, Predictive Analytics & Data-Driven Decision-Making, Blockchain & Cybersecurity in Supply Chains.',
    'href' => 'https://aapscm.org/chartered-supply-chain-artificial-intelligence-csai/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/02/1-4.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-18.png',
  ),
  43 =>
  array (
    'title' => 'American Certified AI Supply Chain Resilience & Crisis Manager (AC-AISCRC)®',
    'desc' => 'Overview: The Certified AI Supply Chain Resilience & Crisis Manager (AC-AISCRC)® certification, offered by the American Association of Procurement, Supply Chain, and Tourism Management (AAPSCM®), is a premier credential designed for professionals who want to integrate Artificial Intelligence (AI), predictive analytics, and crisis management frameworks into supply chain resilience strategies. In an era of global disruptions, geopolitical uncertainties, pandemics, cyber threats, and climate-related risks, supply chains must be proactive, resilient, and AI-powered to ensure operational continuity. The AC-AISCRC® certification provides professionals with AI-driven risk intelligence, real-time crisis response strategies, and predictive supply chain resilience frameworks to anticipate and mitigate disruptions effectively.',
    'href' => 'https://aapscm.org/american-certified-ai-supply-chain-resilience-amp-crisis-manager-ac-aiscrc/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-4-1.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-84.png',
  ),
  44 =>
  array (
    'title' => 'American Certified AI & Blockchain Procurement Professional (AC-AIBPP)®',
    'desc' => 'Overview:The Certified AI & Blockchain Procurement Professional (AC-AIBPP)® certification, offered by the American Association of Procurement, Supply Chain, and Tourism Management (AAPSCM®), is a cutting-edge credential designed for professionals seeking to leverage Artificial Intelligence (AI) and Blockchain to revolutionize procurement processes.With AI enhancing procurement automation, predictive analytics, and supplier management and blockchain ensuring secure, transparent, and tamper-proof transactions, procurement professionals must adopt these transformative technologies to optimize efficiency and reduce fraud risks. The AC-AIBPP® certification provides professionals with AI-driven procurement automation skills, smart contract development expertise, and blockchain-powered risk mitigation strategies to lead the future of digital procurement.',
    'href' => 'https://aapscm.org/american-certified-ai-amp-blockchain-procurement-professional-ac-aibpp/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-86.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-87.png',
  ),
  45 =>
  array (
    'title' => 'American Certified AI Procurement Demand & Forecasting Analyst (AC-AIPDFA)®',
    'desc' => 'Overview: The American Certified AI Procurement Demand & Forecasting Analyst (AC-AIPDFA)® certification, offered by the American Association of Procurement, Supply Chain, and Tourism Management (AAPSCM®), is a premier credential for professionals who want to integrate Artificial Intelligence (AI), machine learning, and predictive analytics into procurement demand planning and forecasting. With rapidly evolving global markets, procurement professionals must leverage AI-driven demand prediction models, real-time data analytics, and automated procurement forecasting tools to optimize sourcing decisions and reduce supply chain disruptions. The ACAIPDFA® certification provides professionals with the skills to implement AI-powered demand forecasting models, automate procurement planning, and optimize inventory and supplier strategies.',
    'href' => 'https://aapscm.org/american-certified-ai-procurement-demand-amp-forecasting-analyst-ac-aipdfa/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-88.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-89.png',
  ),
  46 =>
  array (
    'title' => 'American Certified AI Procurement Chatbot & Supplier Relations Professional (AC-AIPCSR)®',
    'desc' => 'Overview:The American Certified AI Procurement Chatbot & Supplier Relations Professional (AC-AIPCSR)® certification, offered by the American Association of Procurement, Supply Chain, and Tourism Management (AAPSCM®), is a cutting-edge credential for professionals who want to leverage Artificial Intelligence (AI), Natural Language Processing (NLP), and chatbot automation to enhance supplier relations and procurement communications.In today’s fast-paced procurement landscape, AI-powered chatbots are transforming supplier interactions, automating negotiations, handling procurement queries, and optimizing supplier engagement. The AC-AIPCSR® certification equips professionals with expertise in AI-driven supplier communication, chatbot deployment, and intelligent contract automation, helping organizations improve supplier relationships and procurement efficiency.',
    'href' => 'https://aapscm.org/american-certified-ai-procurement-chatbot-amp-supplier-relations-professional-ac-aipcsr/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-4-2.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-101.png',
  ),
  47 =>
  array (
    'title' => 'Certified AI Procurement Chatbot & Supplier Relations Professional (CAIP-CSRP)®',
    'desc' => 'Focus:AI-powered chatbots, supplier communication automation, and procurement workflow AI.',
    'href' => 'https://aapscm.org/american-certified-ai-procurement-chatbot-amp-supplier-relations-professional-ac-aipcsr/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/02/10-2.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/03/1-17.png',
  ),
  48 =>
  array (
    'title' => 'American Certified Supply Chain Artificial Intelligence (AI) Professional – AC-SCAI®',
    'desc' => 'The American Certified Supply Chain Artificial Intelligence (AI) Professional – AC-SCAI® is a globally recognized credential designed for professionals who……..',
    'href' => 'https://aapscm.org/american-certified-supply-chain-artificial-intelligence-ai-professional-ac-scai/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/10/american.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/10/professional-badge.jpg',
  ),
  49 =>
  array (
    'title' => 'Chartered Supply Chain Artificial Intelligence Manager (CSAI-M®)',
    'desc' => 'The Chartered Supply Chain Artificial Intelligence Manager (CSAI-M®) is AAPSCM’s flagship advanced credential for professionals who lead digital transformation in supply-chain intelligence. This program………',
    'href' => 'https://aapscm.org/chartered-supply-chain-artificial-intelligence-manager-csai-m/',
    'top_image' => 'https://aapscm.org/wp-content/uploads/2025/10/logo-Chartered-Supply-Chain-Artificial-Intelligence-Manager-CSAI-M®.png',
    'badge_image' => 'https://aapscm.org/wp-content/uploads/2025/10/chartered-badge.jpg',
  ),
);
