<?php
/**
 * One-off extraction script for /all-courses/ page.
 * Parses the saved HTML and outputs all_courses_cards.php data file.
 *
 * Usage: php database/seeders/data/extract_all_courses.php
 */

$html = file_get_contents('D:/Personal Work/Live Pages HTML/all-courses.html');
if (!$html) { die("Cannot read HTML file.\n"); }

// Extract only the main page content (between data-elementor-id="1464" and the footer)
preg_match('/data-elementor-id="1464"(.*?)(?:<footer|$)/s', $html, $pageContent);
$content = $pageContent[1] ?? $html;

// Find all section headings (H3 in elementor-heading-title)
$sectionNames = [
    'Procurement Certifications',
    'Supply Chain certifications',
    'Tourism Management',
    'E-Commerce Management &amp; Administration',
    'AI courses',
];

// Find all image-box widgets (each is a card)
preg_match_all(
    '/<div class="elementor-image-box-wrapper">.*?<\/div>\s*<\/div>\s*<\/div>/s',
    $content,
    $imageBoxes,
    PREG_OFFSET_CAPTURE
);

// Find button links (Learn More)
preg_match_all(
    '/elementor-button-link elementor-size-sm" href="([^"]+)".*?<span class="elementor-button-text">Learn More/s',
    $content,
    $buttons,
    PREG_OFFSET_CAPTURE
);

// Find section heading positions
$sectionPositions = [];
foreach ($sectionNames as $name) {
    $escaped = preg_quote($name, '/');
    if (preg_match('/elementor-heading-title elementor-size-default">' . $escaped . '/s', $content, $m, PREG_OFFSET_CAPTURE)) {
        $sectionPositions[] = ['name' => html_entity_decode($name), 'offset' => $m[0][1]];
    }
}

// Build cards by pairing each image-box with its nearest following button
$cards = [];
foreach ($imageBoxes[0] as $idx => $match) {
    $boxHtml = $match[0];
    $boxOffset = $match[1];

    // Extract image src
    $imgSrc = '';
    if (preg_match('/(?:elementor-image-box-img.*?)<img[^>]+src="([^"]+)"/s', $boxHtml, $imgM)) {
        $imgSrc = $imgM[1];
    }

    // Extract title (from elementor-image-box-title)
    $title = '';
    if (preg_match('/elementor-image-box-title[^>]*>(?:<a[^>]*>)?(.*?)(?:<\/a>)?<\/h3>/s', $boxHtml, $titleM)) {
        $title = trim(html_entity_decode(strip_tags($titleM[1]), ENT_QUOTES | ENT_HTML5, 'UTF-8'));
    }

    // Find the nearest Learn More button after this image-box
    $href = '#';
    foreach ($buttons[1] as $bIdx => $bMatch) {
        if ($buttons[0][$bIdx][1] > $boxOffset) {
            // Check this button is close enough (within 500 chars)
            if ($buttons[0][$bIdx][1] - $boxOffset < 2000) {
                $href = $bMatch[0];
            }
            break;
        }
    }

    if (empty($title)) continue;

    // Determine section
    $section = 'unknown';
    for ($s = count($sectionPositions) - 1; $s >= 0; $s--) {
        if ($boxOffset > $sectionPositions[$s]['offset']) {
            $section = $sectionPositions[$s]['name'];
            break;
        }
    }

    $cards[] = [
        'section' => $section,
        'title'   => $title,
        'image'   => $imgSrc,
        'href'    => $href,
    ];
}

// Group by section
$grouped = [];
foreach ($cards as $c) {
    $grouped[$c['section']][] = $c;
}

// Output
echo "Sections found: " . implode(', ', array_keys($grouped)) . "\n";
foreach ($grouped as $sec => $items) {
    echo "  $sec: " . count($items) . " cards\n";
}
echo "Total: " . count($cards) . " cards\n\n";

// Write the PHP data file
$output = "<?php\n\ndeclare(strict_types=1);\n\n";
$output .= "/**\n * Extracted card data for /all-courses/ page.\n";
$output .= " * Auto-generated by extract_all_courses.php � do not edit by hand.\n */\n\n";
$output .= "return [\n";

foreach ($grouped as $section => $items) {
    $output .= "    // " . str_repeat('-', 60) . "\n";
    $output .= "    // $section\n";
    $output .= "    // " . str_repeat('-', 60) . "\n";
    foreach ($items as $c) {
        $t = addcslashes($c['title'], "'");
        $i = addcslashes($c['image'], "'");
        $h = addcslashes($c['href'], "'");
        $output .= "    [\n";
        $output .= "        'section' => '$section',\n";
        $output .= "        'title'   => '$t',\n";
        $output .= "        'image'   => '$i',\n";
        $output .= "        'href'    => '$h',\n";
        $output .= "    ],\n";
    }
}

$output .= "];\n";

file_put_contents(__DIR__ . '/all_courses_cards.php', $output);
echo "Written to database/seeders/data/all_courses_cards.php\n";
