<?php
/**
 * One-off extraction script for /aapscm-training/ page.
 * Parses the saved HTML and outputs aapscm_training_cards.php data file.
 *
 * Usage: php database/seeders/data/extract_aapscm_training.php
 */

$html = file_get_contents('D:/Personal Work/Live Pages HTML/aapscm-training.html');
if (!$html) { die("Cannot read HTML file.\n"); }

// Find all box-traning sections (each = one training card)
preg_match_all(
    '/box-traning.*?<img[^>]+src="([^"]+)".*?<a href="([^"]+)"[^>]*>(.*?)<\/a>/s',
    $html,
    $matches,
    PREG_SET_ORDER
);

$cards = [];
$seen = [];
foreach ($matches as $m) {
    $image = trim($m[1]);
    $href  = trim($m[2]);
    $title = trim(strip_tags(html_entity_decode($m[3], ENT_QUOTES | ENT_HTML5, 'UTF-8')));
    // Remove trailing arrow icon remnant
    $title = preg_replace('/\s*$/', '', $title);

    // Deduplicate by href
    if (isset($seen[$href])) continue;
    $seen[$href] = true;

    $cards[] = [
        'title' => $title,
        'image' => $image,
        'href'  => $href,
    ];
}

echo "Total cards: " . count($cards) . "\n\n";
foreach ($cards as $i => $c) {
    echo sprintf("%2d. %s\n    img: %s\n    href: %s\n\n", $i+1, $c['title'], $c['image'], $c['href']);
}

// Write data file
$outPath = 'D:/Personal Work/AAPSCM-LARAVEL/database/seeders/data/aapscm_training_cards.php';
$output = "<?php\n\ndeclare(strict_types=1);\n\n";
$output .= "/**\n * Extracted training schedule card data for /aapscm-training/ page.\n";
$output .= " * Auto-generated by extract_aapscm_training.php - do not edit by hand.\n */\n\n";
$output .= "return " . var_export($cards, true) . ";\n";

file_put_contents($outPath, $output);
echo "Written to: $outPath\n";
