<?php

/**
 * One-off parser: extracts certification cards from the live HTML snapshot
 * (d:\Personal Work\Live Pages HTML\certifications-for-professionals.html)
 * and writes a structured PHP array to
 * database/seeders/data/certifications_for_professionals_cards.php.
 *
 * Usage:  php database/seeders/data/extract_certifications_for_professionals.php
 *
 * The seeder reads the generated file; this script is not invoked at runtime.
 */

declare(strict_types=1);

$htmlPath = dirname(__DIR__, 3) . DIRECTORY_SEPARATOR . '..'
          . DIRECTORY_SEPARATOR . 'Live Pages HTML'
          . DIRECTORY_SEPARATOR . 'certifications-for-professionals.html';

if (! is_file($htmlPath)) {
    fwrite(STDERR, "HTML snapshot not found at: {$htmlPath}\n");
    exit(1);
}

$html = (string) file_get_contents($htmlPath);

// Isolate the main content block (between the title bar and the footer).
$start = strpos($html, 'eltdf-page-title');
$end   = strpos($html, '<footer');
if ($start === false || $end === false) {
    fwrite(STDERR, "Could not locate content region.\n");
    exit(1);
}
$body = substr($html, $start, $end - $start);

// Each card is a "box-all" inner-section containing widgets in order:
//   image (top illustration) → heading (title) → text-editor (desc)
//   → button (Learn More link) → image (badge).
//
// We split on the box-all boundary, then pick widgets out of each block.
$blocks = preg_split('/elementor-inner-section[^"]*box-all[^"]*/i', $body);
if ($blocks === false) {
    fwrite(STDERR, "Failed splitting on box-all.\n");
    exit(1);
}

$cards = [];

foreach ($blocks as $block) {
    // Top illustration: first <img> in block.
    if (! preg_match(
        '#<img[^>]*src="(https?://[^"]+/wp-content/uploads/[^"]+\.(?:png|jpe?g|webp|gif))"[^>]*>#i',
        $block,
        $topImgMatch,
    )) {
        continue;
    }
    $topImage = $topImgMatch[1];

    // Title: first <h2> with an elementor-heading-title class.
    if (! preg_match(
        '#<h2[^>]*elementor-heading-title[^>]*>(.*?)</h2>#is',
        $block,
        $titleMatch,
    )) {
        continue;
    }
    $titleRaw = $titleMatch[1];

    // Strip wrapping <a> if present (some titles are anchored) but keep inner text.
    $title = trim(strip_tags($titleRaw));
    $title = html_entity_decode($title, ENT_QUOTES | ENT_HTML5, 'UTF-8');
    $title = preg_replace('/\s+/', ' ', $title);
    // Remove trailing ">" artefact that some titles have from the live page.
    $title = rtrim($title, '> ');

    // Description: first text-editor widget body.
    $desc = '';
    if (preg_match(
        '#elementor-widget-text-editor.*?elementor-widget-container">\s*(.*?)\s*</div>#is',
        $block,
        $descMatch,
    )) {
        $desc = trim(strip_tags($descMatch[1]));
        $desc = html_entity_decode($desc, ENT_QUOTES | ENT_HTML5, 'UTF-8');
        $desc = preg_replace('/\s+/', ' ', $desc);
    }

    // Link: first "elementor-button" href inside the block.
    $href = '#';
    if (preg_match(
        '#<a\s+class="elementor-button[^"]*"\s+href="([^"]+)"#i',
        $block,
        $hrefMatch,
    )) {
        $href = $hrefMatch[1];
    }

    // Badge image: second <img> in the block (if present).
    $badgeImage = null;
    if (preg_match_all(
        '#<img[^>]*src="(https?://[^"]+/wp-content/uploads/[^"]+\.(?:png|jpe?g|webp|gif))"[^>]*>#i',
        $block,
        $allImgs,
    ) && count($allImgs[1]) >= 2) {
        $badgeImage = $allImgs[1][1];
    }

    $cards[] = [
        'title'        => $title,
        'desc'         => $desc,
        'href'         => $href,
        'top_image'    => $topImage,
        'badge_image'  => $badgeImage,
    ];
}

// Sanity: dedupe by (title + top_image) in case splitting picks up an artefact.
$seen = [];
$out  = [];
foreach ($cards as $c) {
    $key = $c['title'] . '|' . $c['top_image'];
    if (isset($seen[$key])) {
        continue;
    }
    $seen[$key] = true;
    $out[]      = $c;
}

$outFile = __DIR__ . DIRECTORY_SEPARATOR . 'certifications_for_professionals_cards.php';

$body = "<?php\n\n"
      . "// Auto-generated by extract_certifications_for_professionals.php\n"
      . "// Source: ../../../Live Pages HTML/certifications-for-professionals.html\n"
      . "// Do not hand-edit — re-run the extractor if the live page changes.\n\n"
      . "return " . var_export($out, true) . ";\n";

file_put_contents($outFile, $body);

fwrite(STDOUT, count($out) . " card(s) extracted → {$outFile}\n");
