<?php

declare(strict_types=1);

/**
 * Extracted content for /workshop-trainings/ page (mirrored from aapscm.com).
 * Auto-generated by parse_workshop_trainings.php - do not edit by hand.
 */

return 
array (
  'page_title' => 'Workshop Trainings',
  'hero' => 
  array (
    'h3' => 'Workshop & Trainings',
    'h5' => 'SEE WHICH CERTIFICATION IS RIGHT FOR YOU',
  ),
  'row1' => 
  array (
    'heading' => 'What Management Careers Can You Pursue with AAPSCM® Certifications?',
    'image' => 'https://aapscm.com/wp-content/uploads/2025/01/1-20.png',
    'text' => 'AAPSCM® certifications are designed to validate the skills required for a wide range of management roles across procurement, supply chain, and tourism industries. As the only Chartered Certifications Board that recognizes Hospitality and Tourism Management as a professional skilled workforce, AAPSCM® is committed to promoting and accrediting excellence in these vital sectors. Our goal is to uphold and advance high standards of professional skill, ability, and integrity among those engaged in Procurement, Sustainability, Supply Chain, and Tourism Management',
  ),
  'row2' => 
  array (
    'image' => 'https://aapscm.com/wp-content/uploads/2025/01/1-21.png',
    'texts' => 
    array (
      0 => 'AAPSCM® drives industry growth through tailored training programs, globally recognized certifications, market research, and a commitment to philanthropy. By fostering innovation and developing a highly skilled workforce, AAPSCM® enables professionals to master the essentials of delivering the right quality, quantity, and price to the right place and time. Our ultimate aim is to empower professionals with the expertise to mitigate risks, avoid supply disruptions, and establish contingency plans in the complex landscape of global commerce.',
      1 => 'Whether you’re exploring entry-level roles or advancing toward senior management, AAPSCM® certifications open doors to dynamic career opportunities. From procurement analysts to supply chain managers and tourism directors, our certifications offer a clear path for career growth. Use our Management Career Roadmap to explore how AAPSCM® certifications align with your professional goals, helping you plot the next step in your career journey.',
      2 => 'Learn more about how AAPSCM® certifications can position you for leadership roles and provide the skills to excel in a competitive global market. Take the next step today and discover what’s possible with AAPSCM®.',
    ),
    'button' => 
    array (
      'text' => 'PLAN YOUR NEXT MOVE',
      'href' => 'https://aapscm.com/membership/',
    ),
  ),
  'tables' => 
  array (
    'procurement' => 
    array (
      'heading_prefix' => 'Procurement',
      'heading_bold' => 'Management',
      'rows' => 
      array (
        0 => 
        array (
          'certification' => 'American Certified Procurement Professional  (ACPP)®',
          'certification_html' => 'American Certified Procurement Professional <strong> (ACPP)®</strong>',
          'focus' => 'Procurement fundamentals, sourcing strategies, supplier relationship management, e-procurement.',
          'href' => 'https://aapscm.com/acpp/',
        ),
        1 => 
        array (
          'certification' => 'Chartered Procurement Manager (CPM)®',
          'certification_html' => 'Chartered Procurement Manager <strong>(CPM)®</strong>',
          'focus' => 'Strategic sourcing, procurement ethics, advanced supplier relationship',
          'href' => 'https://aapscm.com/american-certified-procurement-manager-acpm/',
        ),
        2 => 
        array (
          'certification' => 'American Certified Digital Procurement & Analytics Professional (AC-DPA)®',
          'certification_html' => 'American Certified Digital Procurement &amp; Analytics Professional <strong>(AC-DPA)®</strong>',
          'focus' => 'Digital procurement strategies, analytics integration, and process optimization.',
          'href' => 'https://aapscm.com/american-certified-digital-procurement-analytics-specialist/',
        ),
        3 => 
        array (
          'certification' => 'Sustainable Green Procurement & Ethical Sourcing Professional (AC-SGPES)®',
          'certification_html' => 'Sustainable Green Procurement &amp; Ethical Sourcing Professional <strong>(AC-SGPES)®</strong>',
          'focus' => 'Sustainable procurement, ethical sourcing, and corporate social responsibility.',
          'href' => 'https://aapscm.com/american-certified-sustainable-procurement-ethical-sourcing-professional/',
        ),
        4 => 
        array (
          'certification' => 'American Certified Procurement Risk Management Professional(AC-PRM)®',
          'certification_html' => 'American Certified Procurement Risk Management Professional<strong>(AC-PRM)®</strong>',
          'focus' => 'Risk management, procurement planning, and mitigation strategies.',
          'href' => 'https://aapscm.com/american-certified-procurement-risk-management-specialist/',
        ),
        5 => 
        array (
          'certification' => 'American Certified Strategic Procurement & Supplier Relationship Professional (AC-SPR)®',
          'certification_html' => 'American Certified Strategic Procurement &amp; Supplier Relationship Professional <strong>(AC-SPR)®</strong>',
          'focus' => 'Strategic procurement, supplier partnerships, and process improvement.',
          'href' => 'https://aapscm.com/american-certified-strategic-procurement-supplier-relationship-specialist/',
        ),
        6 => 
        array (
          'certification' => 'Chartered Strategic Procurement & Supplier Relationship Manager (CSP-SRM)®',
          'certification_html' => 'Chartered Strategic Procurement &amp; Supplier Relationship Manager <strong>(CSP-SRM)®</strong>',
          'focus' => 'Advanced supplier relationship management, strategy formulation, and execution.',
          'href' => 'https://aapscm.com/chartered-strategic-procurement-supplier-relationship-specialist/',
        ),
        7 => 
        array (
          'certification' => 'American Certified IT Procurement & Digital Transformation Professional (ACIPDT)®',
          'certification_html' => 'American Certified IT Procurement &amp; Digital Transformation Professional <strong>(ACIPDT)®</strong>',
          'focus' => 'IT procurement, digital transformation in procurement, and innovation strategies.',
          'href' => 'https://aapscm.com/american-certified-it-procurement-digital-transformation-specialist/',
        ),
        8 => 
        array (
          'certification' => 'American Certified Public Sector Procurement & Compliance Professional (AC-PSPC)®',
          'certification_html' => 'American Certified Public Sector Procurement &amp; Compliance Professional <strong>(AC-PSPC)®</strong>',
          'focus' => 'Public sector procurement, regulatory compliance, and transparency.',
          'href' => 'https://aapscm.com/american-certified-public-sector-procurement-compliance-specialist/',
        ),
        9 => 
        array (
          'certification' => 'American Certified Global Procurement & Cross-Border Supply Professional (AC-GPCS)®',
          'certification_html' => 'American Certified Global Procurement &amp; Cross-Border Supply Professional <strong>(AC-GPCS)®</strong>',
          'focus' => 'Global procurement, cross-border trade management, and international compliance.',
          'href' => 'https://aapscm.com/american-certified-global-procurement-cross-border-supply-specialist-ac-gpcss/',
        ),
        10 => 
        array (
          'certification' => 'Chartered AI-Driven Sustainable Procurement Manager (CAI-SPM)®',
          'certification_html' => 'Chartered AI-Driven Sustainable Procurement Manager <strong>(CAI-SPM)®</strong>',
          'focus' => 'AI-driven sustainable procurement practices and innovation strategies for long-term success.',
          'href' => 'https://aapscm.com/chartered-ai-driven-sustainable-procurement-manager-ca-ispm/',
        ),
        11 => 
        array (
          'certification' => 'American Certified Procurement Data Science & AI Professional (AC-PDS)®',
          'certification_html' => 'American Certified Procurement Data Science &amp; AI Professional <strong>(AC-PDS)®</strong>',
          'focus' => 'Application of data science and AI in procurement analytics and decision-making.',
          'href' => 'https://aapscm.com/american-certified-procurement-data-science-ai-specialist-ac-pdss/',
        ),
        12 => 
        array (
          'certification' => 'American Certified Procurement Leadership & Change Management Professional (AC-PLCMS)®',
          'certification_html' => 'American Certified Procurement Leadership &amp; Change Management Professional <strong>(AC-PLCMS)®</strong>',
          'focus' => 'Procurement leadership, change management strategies, and organizational transformation.',
          'href' => 'https://aapscm.com/american-certified-procurement-leadership-change-management-specialist/',
        ),
        13 => 
        array (
          'certification' => 'American Certified Procurement Automation & RPA Professional (AC-PARP)®',
          'certification_html' => 'American Certified Procurement Automation &amp; RPA Professional <strong>(AC-PARP)®</strong>',
          'focus' => 'Procurement process automation, robotic process automation (RPA), and technology-driven efficiency.',
          'href' => 'https://aapscm.com/american-certified-procurement-automation-rpa-specialist-ac-paras-2/',
        ),
        14 => 
        array (
          'certification' => 'Chartered Healthcare Procurement Solutions Professional (CHPP)®',
          'certification_html' => 'Chartered Healthcare Procurement Solutions Professional <strong>(CHPP)®</strong>',
          'focus' => 'The Chartered Healthcare Procurement Solutions Professional (CHPP)® exam will focus on advanced procurement strategies within the healthcare sector, emphasizing regulatory compliance, strategic sourcing, contract management, cost efficiency, supply chain optimization, risk mitigation, and fostering innovation to meet the unique demands of healthcare procurement and patient care delivery.',
          'href' => 'https://aapscm.com/chartered-healthcare-procurement-solutions-professional-chpp/',
        ),
      ),
    ),
    'ecommerce' => 
    array (
      'heading_prefix' => 'E-Commerce',
      'heading_bold' => 'Management & Administration',
      'rows' => 
      array (
        0 => 
        array (
          'certification' => 'American Certified E-Commerce Strategy and Growth Professional (AC-ESGP)®',
          'certification_html' => 'American Certified E-Commerce Strategy and Growth Professional <strong>(AC-ESGP)® </strong>',
          'focus' => 'The AC-ESGP® certification examevaluates your expertise in developing and implementing e-commerce strategies, driving business growth, leveraging emerging technologies, and optimizing operations to achieve measurable success in the digital marketplace.',
          'href' => 'https://aapscm.com/american-certified-e-commerce-strategy-and-growth-professional-ac-esgp/',
        ),
        1 => 
        array (
          'certification' => 'Chartered E-Commerce Data Analytics and AI Professional (CED-AI)®',
          'certification_html' => 'Chartered E-Commerce Data Analytics and AI Professional <strong>(CED-AI)®</strong>',
          'focus' => 'The CED-AI® certification exam assesses your proficiency in leveraging data analytics and AI-driven solutions to optimize e-commerce operations, enhance customer experiences, predict trends, and drive strategic decision-making in digital commerce.',
          'href' => 'https://aapscm.com/chartered-e-commerce-data-analytics-and-ai-professional-ced-ai/',
        ),
        2 => 
        array (
          'certification' => 'Chartered Global Cross-Border E-Commerce Manager (CGCBE)®',
          'certification_html' => 'Chartered Global Cross-Border E-Commerce Manager <strong>(CGCBE)® </strong>',
          'focus' => 'The CGCBE® certification exam evaluates your expertise in managing cross-border e-commerce operations, including global market entry strategies, regulatory compliance, logistics optimization, and localization for diverse international markets.',
          'href' => 'https://aapscm.com/chartered-global-cross-border-e-commerce-manager-cgcbe/',
        ),
        3 => 
        array (
          'certification' => 'American Certified Ethical Practices & Sustainable E-Commerce Professional (AC-SEEP)®',
          'certification_html' => 'American Certified Ethical Practices &amp; Sustainable E-Commerce Professional <strong>(AC-SEEP)®</strong>',
          'focus' => 'The AC-DMUX® certification exam focuses on assessing your expertise in digital merchandising strategies, user experience optimization, data-driven decision-making, and the application of innovative and sustainable e-commerce practices.',
          'href' => 'https://aapscm.com/american-certified-ethical-practices-sustainable-e-commerce-professional-ac-seep/',
        ),
        4 => 
        array (
          'certification' => 'American Certified Digital Merchandising and User Experience Professional (AC-DMUX)®',
          'certification_html' => 'American Certified Digital Merchandising and User Experience Professional <strong>(AC-DMUX)®</strong>',
          'focus' => 'The AC-DMUX® certification exam focuses on assessing your expertise in digital merchandising strategies, user experience optimization, data-driven decision-making, and the application of innovative and sustainable e-commerce practices.',
          'href' => 'https://aapscm.com/american-certified-digital-merchandising-and-user-experience-professional-ac-dmux/',
        ),
      ),
    ),
    'tourism' => 
    array (
      'heading_prefix' => 'Tourism',
      'heading_bold' => 'Management',
      'rows' => 
      array (
        0 => 
        array (
          'certification' => 'American Certified Tourism Professional (ACTP)®',
          'certification_html' => 'American Certified Tourism Professional <strong>(ACTP)®</strong>',
          'focus' => 'Tourism management, marketing strategies, and sustainable tourism practices.',
          'href' => 'https://aapscm.com/american-certified-tourism-professional/',
        ),
        1 => 
        array (
          'certification' => 'Chartered Tourism Manager (CTM)®',
          'certification_html' => 'Chartered Tourism Manager <strong>(CTM)®</strong>',
          'focus' => 'Strategic tourism management, policy development, and innovation in the tourism sector.',
          'href' => 'https://aapscm.com/ctm/',
        ),
        2 => 
        array (
          'certification' => 'Chartered Sustainable Culinary Tourism Manager (CSCTM)®',
          'certification_html' => 'Chartered Sustainable Culinary Tourism Manager <strong>(CSCTM)®</strong>',
          'focus' => 'The Sustainable Culinary Tourism certification exam focuses on assessing knowledge and strategies for promoting environmentally sustainable practices, cultural preservation, and economic development within the culinary tourism industry.',
          'href' => 'https://aapscm.com/chartered-sustainable-culinary-tourism-manager-csctm/',
        ),
      ),
    ),
    'supply_chain' => 
    array (
      'heading_prefix' => 'Supply',
      'heading_bold' => 'Chain Managment',
      'rows' => 
      array (
        0 => 
        array (
          'certification' => 'Chartered Supply Chain Manager (CSCM)®',
          'certification_html' => 'Chartered Supply Chain Manager <strong>(CSCM)®</strong>',
          'focus' => 'CSCM® examination tests your managerial capabilities in logistics, digital coordination for supply chain integration, inventory management, risk pooling, procurement, product and process design, and international supply chain management, including logistics, digital coordination of decisions and resources, inventory and risk management, procurement and supply contracting, product and process design, and revenue management.',
          'href' => 'https://aapscm.com/chartered-supply-chain-manager-acscm/',
        ),
        1 => 
        array (
          'certification' => 'Chartered Supply Chain Technology Manager (CSCT)®',
          'certification_html' => 'Chartered Supply Chain Technology Manager <strong>(CSCT)®</strong>',
          'focus' => 'The new Chartered Supply Chain Technology Manager (CSCT)®certification test focuses on knowledge and skills that would equip professionals with expertise in leveraging advanced technologies, such as AI, IoT, and predictive analytics, to optimize supply chain operations and drive digital transformation.',
          'href' => 'https://aapscm.com/acsct/',
        ),
        2 => 
        array (
          'certification' => 'American Certified Supply Chain Professional (ACSCP)®',
          'certification_html' => 'American Certified Supply Chain Professional <strong>(ACSCP)®</strong>',
          'focus' => 'The ACSCP® Certification tests fundamental concepts of supply chain management. All functional areas of supply chain management are explored in an integrated view of procurement, manufacturing and operations management, transportation and logistics, inventory and warehousing, demand planning, and scheduling.',
          'href' => 'https://aapscm.com/the-american-certified-supply-chain-professional-acscp/',
        ),
        3 => 
        array (
          'certification' => 'Chartered Supply Chain Artiﬁcial Intelligence Professional (CSAI)®',
          'certification_html' => 'Chartered Supply Chain Artiﬁcial Intelligence Professional <strong>(CSAI)®</strong>',
          'focus' => 'The CSAI (Chartered Supply Chain Artificial Intelligence Professional)® certification focuses on applying AI-driven tools and methodologies to enhance supply chain visibility, optimize operations, and drive data-informed decision-making',
          'href' => 'https://aapscm.com/the-american-certified-supply-chain-artificial-intelligence-analyst-acsai/',
        ),
        4 => 
        array (
          'certification' => 'American Certified Sustainable and Circular Supply Chain Professional (AC-CSCSP)®',
          'certification_html' => 'American Certified Sustainable and Circular Supply Chain Professional <strong>(AC-CSCSP)®</strong>',
          'focus' => 'The AC-CSCSP® certification exam focuses on assessing your expertise in designing, implementing, and managing sustainable and circular supply chains, including principles of sustainability, circular economy models, regulatory compliance, and green technologies.',
          'href' => 'https://aapscm.com/american-certified-sustainable-and-circular-supply-chain-professional-ac-cscsp/',
        ),
        5 => 
        array (
          'certification' => 'Chartered Sustainable Supply Chain Manager (CSSCM)®',
          'certification_html' => 'Chartered Sustainable Supply Chain Manager <strong>(CSSCM)®</strong>',
          'focus' => 'The Sustainable Supply Chain Management Certification (CSSCM)® exam assesses your ability to design, implement, and manage eco-friendly and socially responsible procurement and supply chain strategies through practical, scenario-based evaluations.',
          'href' => 'https://aapscm.com/chartered-sustainable-supply-chain-manager-csscm/',
        ),
        6 => 
        array (
          'certification' => 'American Certified Blockchain for Supply Chain Professional(AC-BSCP)®',
          'certification_html' => 'American Certified Blockchain for Supply Chain Professional<strong>(AC-BSCP)®</strong>',
          'focus' => 'The AC-BSCP certification exam evaluates your expertise in leveraging blockchain technology for secure, transparent, and efficient supply chain management through a rigorous, scenario-based assessment.',
          'href' => 'https://aapscm.com/american-certified-blockchain-for-supply-chain-professional-ac-bscp/',
        ),
        7 => 
        array (
          'certification' => 'American Certified Supply Chain Cybersecurity Professional (AC-SCCP)®',
          'certification_html' => 'American Certified Supply Chain Cybersecurity Professional<strong> (AC-SCCP)®</strong>',
          'focus' => 'The Supply Chain Cybersecurity Professional Certification exam tests your ability to secure supply chain systems against cyber threats through comprehensive, real-world scenario assessments.',
          'href' => 'https://aapscm.com/american-certified-supply-chain-cybersecurity-professional-ac-sccp/',
        ),
        8 => 
        array (
          'certification' => 'Chartered Advanced Supply Chain Cybersecurity Manager (CA-SCCM)®',
          'certification_html' => 'Chartered Advanced Supply Chain Cybersecurity Manager <strong>(CA-SCCM)®</strong>',
          'focus' => 'The Supply Chain Cybersecurity Professional Certification (CA-SCCM)®exam assesses your proficiency in safeguarding supply chain networks and data against cyber threats through practical, scenario-based evaluations.',
          'href' => 'https://aapscm.com/chartered-advanced-supply-chain-cybersecurity-manager-ca-sccm/',
        ),
        9 => 
        array (
          'certification' => 'American Certified Digital Supply Chain Integration Professional (AC-DSCI)®',
          'certification_html' => 'American Certified Digital Supply Chain Integration Professional <strong>(AC-DSCI)®</strong>',
          'focus' => 'The American Certified Digital Supply Chain Integration Professional Certification (AC-DSIP)® exam evaluates your proficiency in integrating digital technologies to optimize and streamline supply chain operations through practical, scenario-based assessments.',
          'href' => 'https://aapscm.com/american-certified-digital-supply-chain-integration-professional-ac-dscip/',
        ),
        10 => 
        array (
          'certification' => 'American Certified Supply Chain Digital Transformation Manager (AC-SCDTM)®',
          'certification_html' => 'American Certified Supply Chain Digital Transformation Manager<strong> (AC-SCDTM)®</strong>',
          'focus' => 'The AC-SCDTM® certification exam evaluates your ability to design and implement digital transformation strategies, integrate advanced technologies, and drive efficiency, visibility, and sustainability in global supply chain operations.',
          'href' => 'https://aapscm.com/american-certified-supply-chain-digital-transformation-manager-ac-scdtm/',
        ),
        11 => 
        array (
          'certification' => 'American Certified Global Supply Chain Risk and Resilience Professional (AC- GSRP)®',
          'certification_html' => 'American Certified Global Supply Chain Risk and Resilience Professional<strong> (AC- GSRP)®</strong>',
          'focus' => 'The American Certified Global Supply Chain Risk and Resilience Professional Certification (AC-GSRP)® exam assesses your expertise in identifying, mitigating, and managing supply chain risks while building resilient and adaptive supply chain strategies through real-world, scenario-based evaluations.',
          'href' => 'https://aapscm.com/american-certified-global-supply-chain-risk-and-resilience-professionalac-gsrp/',
        ),
      ),
    ),
    'combined' => 
    array (
      'heading_prefix' => 'Combined Procurement, Logistics,',
      'heading_bold' => 'and Supply Chain Certifications',
      'rows' => 
      array (
        0 => 
        array (
          'certification' => 'American Certified Global Procurement, Logistics & Supply Chain Professional (AC-GPLSCP)®',
          'certification_html' => 'American Certified Global Procurement, Logistics &amp; Supply Chain Professional <strong>(AC-GPLSCP)®</strong>',
          'focus' => 'Global procurement strategies, logistics management, and integrated supply chain operations.',
          'href' => 'https://aapscm.com/american-certified-global-procurement-logistics-amp-supply-chain-professional-ac-gplscp/',
        ),
        1 => 
        array (
          'certification' => 'Chartered Strategic Procurement & Supply Chain Management (CSP-SCM)®',
          'certification_html' => 'Chartered Strategic Procurement &amp; Supply Chain Management <strong>(CSP-SCM)®</strong>',
          'focus' => 'Strategic sourcing, contract management, and end-to-end supply chain optimization.',
          'href' => 'https://aapscm.com/chartered-strategic-procurement-supply-chain-manager-csp-scm/',
        ),
        2 => 
        array (
          'certification' => 'Advanced Certified Procurement, Logistics & Supply Chain Manager (AC-PLSCM)®',
          'certification_html' => 'Advanced Certified Procurement, Logistics &amp; Supply Chain Manager <strong>(AC-PLSCM)®</strong>',
          'focus' => 'Advanced procurement analytics, risk management, and logistics efficiency.',
          'href' => 'https://aapscm.com/advanced-certified-procurement-logistics-supply-chain-manager-ac-plscm/',
        ),
        3 => 
        array (
          'certification' => 'American Certified Sustainable Procurement & Green Supply Chain Professional (AC-SPGSCP)®',
          'certification_html' => 'American Certified Sustainable Procurement &amp; Green Supply Chain Professional <strong>(AC-SPGSCP)®</strong>',
          'focus' => 'Sustainable procurement practices, ethical sourcing, and environmental responsibility in supply chain management.',
          'href' => 'https://aapscm.com/american-certified-sustainable-procurement-amp-green-supply-chain-professional-ac-spgscp/',
        ),
        4 => 
        array (
          'certification' => 'American Certified Digital Supply Chain & Procurement Transformation Professional (AC-DSCPTP)®',
          'certification_html' => 'American Certified Digital Supply Chain &amp; Procurement Transformation Professional <strong>(AC-DSCPTP)®</strong>',
          'focus' => 'Digital supply chain integration, procurement automation, and AI-driven supply chain solutions.',
          'href' => 'https://aapscm.com/american-certified-digital-supply-chain-amp-procurement-transformation-professional-ac-dscptp/',
        ),
        5 => 
        array (
          'certification' => 'American Certified Procurement, Logistics & Transportation Expert (AC-PLTE)®',
          'certification_html' => 'American Certified Procurement, Logistics &amp; Transportation Expert <strong>(AC-PLTE)®</strong>',
          'focus' => 'International logistics, procurement regulations, and global transportation management',
          'href' => 'https://aapscm.com/american-certified-procurement-logistics-transportation-expert-ac-plte/',
        ),
        6 => 
        array (
          'certification' => 'American Certified Agile Procurement & Supply Chain Professional (AC-APSCP)®',
          'certification_html' => 'American Certified Agile Procurement &amp; Supply Chain Professional <strong>(AC-APSCP)®</strong>',
          'focus' => 'Agile procurement strategies, supply chain flexibility, and responsive logistics management.',
          'href' => 'https://aapscm.com/american-certified-agile-procurement-amp-supply-chain-professional-ac-apscp/',
        ),
        7 => 
        array (
          'certification' => 'American Certified Risk & Compliance Professional in Procurement & Supply Chain (AC-RCPPSC)®',
          'certification_html' => 'American Certified Risk &amp; Compliance Professional in Procurement &amp; Supply Chain <strong>(AC-RCPPSC)®</strong>',
          'focus' => 'Risk mitigation, regulatory compliance, procurement, and supply chain operations governance.',
          'href' => 'https://aapscm.com/american-certified-risk-amp-compliance-professional-in-procurement-amp-supply-chain-ac-rcppsc/',
        ),
        8 => 
        array (
          'certification' => 'Executive Diploma in Procurement, Logistics & Supply Chain Leadership (EDPLSCL)®',
          'certification_html' => 'Executive Diploma in Procurement, Logistics &amp; Supply Chain Leadership <strong>(EDPLSCL)®</strong>',
          'focus' => 'Executive-level supply chain leadership, procurement negotiation strategies, and logistics innovation.',
          'href' => 'https://aapscm.com/executive-diploma-in-procurement-logistics-supply-chain-leadership-edplscl/',
        ),
      ),
    ),
  ),
  'cards' => 
  array (
    0 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2023/10/Untitled-design-3.png',
      'title' => 'American Certified Procurement Professional (ACPP)®',
      'description' => 'American Certifed Procurement Professional (ACPP)® certification shows future employers that you have the …',
      'href' => 'https://aapscm.com/hyperlink-1/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/12/3-2.png',
    ),
    1 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2023/12/1.png',
      'title' => 'Chartered Procurement Manager (CPM)®',
      'description' => 'The American Certified Procurement Manager (CPM)® tests knowledge and skills of a procurement manager.',
      'href' => 'https://aapscm.com/american-certified-procurement-manager-acpm/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2023/12/CPM.png',
    ),
    2 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2023/10/Untitled-design-8.png',
      'title' => 'American Certified Supply Chain Professional (ACSCP)®',
      'description' => 'The American Certified Supply Chain Professional …',
      'href' => 'https://aapscm.com/the-american-certified-supply-chain-professional-acscp/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/12/2-3.png',
    ),
    3 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2023/12/2.png',
      'title' => 'Chartered Supply Chain Manager (CSCM)®',
      'description' => 'The American Certified Supply Chain Manager (CSCM®) certification shows future employers that you have the …',
      'href' => 'https://aapscm.com/chartered-supply-chain-manager-acscm/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2023/12/CSCM.png',
    ),
    4 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2023/11/111.jpg',
      'title' => 'Chartered Supply Chain Artiﬁcial Intelligence Professional (CSAI)®',
      'description' => 'The CSAI® certification is internationally recognized and focuses on the examination of end-to-end (E2E) visibility in supply chains.',
      'href' => 'https://aapscm.com/the-american-certified-supply-chain-artificial-intelligence-analyst-acsai/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2023/12/CSAI.png',
    ),
    5 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/12/1-5.png',
      'title' => 'American Certified Digital Procurement & Analytics Professional (AC-DPA)®',
      'description' => 'This program would focus on the intersection..',
      'href' => 'https://aapscm.com/american-certified-digital-procurement-analytics-specialist/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/1-17.png',
    ),
    6 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/12/1-39.png',
      'title' => 'Sustainable Green Procurement & Ethical Sourcing Professional (AC-SGPES)®',
      'description' => 'With an increasing focus on sustainability, this program would educate professionals on green procurement practices, sourcing..',
      'href' => 'https://aapscm.com/american-certified-sustainable-procurement-ethical-sourcing-professional/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/2-4.png',
    ),
    7 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/12/2-1.png',
      'title' => 'American Certified Procurement Risk Management Professional(AC-PRM)®',
      'description' => 'This program would specialize in identifying, assessing, and managing procurement risks, such as supply chain disruptions, geopolitical factors, and….',
      'href' => 'https://aapscm.com/american-certified-procurement-risk-management-specialist/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/4-2.png',
    ),
    8 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/12/3-1.png',
      'title' => 'American Certified Strategic Procurement & Supplier Relationship Professional (AC-SPR)®',
      'description' => 'In today’s competitive landscape….',
      'href' => 'https://aapscm.com/american-certified-strategic-procurement-supplier-relationship-specialist/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/5-2.png',
    ),
    9 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/11/8-2.jpg',
      'title' => 'Chartered Strategic Procurement & Supplier Relationship Manager(CSP-SRM)®',
      'description' => 'Strategic Procurement and Supplier Relationship Management (CSP-SRM) is a critical aspect of modern supply chain…',
      'href' => 'https://aapscm.com/chartered-strategic-procurement-supplier-relationship-specialist/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/8-2.png',
    ),
    10 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/12/4-2.png',
      'title' => 'American Certified IT Procurement & Digital Transformation Professional(ACIPDT)®',
      'description' => 'As organizations continue to digitize, the..',
      'href' => 'https://aapscm.com/american-certified-it-procurement-digital-transformation-specialist/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/6-3.png',
    ),
    11 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/12/5.png',
      'title' => 'American Certified Public Sector Procurement & Compliance Professional(AC-PSPC)®',
      'description' => 'Procurement in the public sector requires…',
      'href' => 'https://aapscm.com/american-certified-public-sector-procurement-compliance-specialist/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/7-2.png',
    ),
    12 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/12/6.png',
      'title' => 'American Certified Global Procurement & Cross-Border Supply Professional(AC-GPCS)®',
      'description' => 'Global procurement introduces unique challenges and opportunities.',
      'href' => 'https://aapscm.com/american-certified-global-procurement-cross-border-supply-specialist-ac-gpcss/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/8-3.png',
    ),
    13 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/12/7.png',
      'title' => 'American Certified Procurement Data Science & AI Professional(AC-PDS)®',
      'description' => 'The AC-PDS Certification is designed for procurement professionals who want to leverage advanced data science and AI..',
      'href' => 'https://aapscm.com/american-certified-procurement-data-science-ai-specialist-ac-pdss/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/9-1.png',
    ),
    14 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/12/8.png',
      'title' => 'American Certified Procurement Leadership & Change Management Professional (AC-PLCM)®',
      'description' => 'Effective procurement requires not only..',
      'href' => 'https://aapscm.com/american-certified-procurement-leadership-change-management-specialist/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/11.png',
    ),
    15 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/12/9.png',
      'title' => 'American Certified Procurement Automation & RPA Professional(AC-PARP)®',
      'description' => 'The AC-PARP Certification focuses on leveraging automation and RPA technologies to transform traditional procurement practices. It is designed ..',
      'href' => 'https://aapscm.com/american-certified-procurement-automation-rpa-specialist-ac-paras-2/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/13.png',
    ),
    16 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/07/11.png',
      'title' => 'American Certified Tourism Professional (ACTP)®',
      'description' => 'Tourism is one of the world’s leading industries and a major economic development tool, and as such, security (crime and terrorism) has a major..',
      'href' => 'https://aapscm.com/american-certified-tourism-professional/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/12/1-8.png',
    ),
    17 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2023/11/33.jpg',
      'title' => 'Chartered Supply Chain Technology Manager (CSCT)®',
      'description' => 'The CSCT® certification is highly sought-after and unique, catering to professionals and managers in both the procurement and supply chain industries.',
      'href' => 'https://aapscm.com/acsct/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2023/12/CSCT.png',
    ),
    18 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2023/10/2222.png',
      'title' => 'Chartered Healthcare Procurement Solutions Professional (CHPP)®',
      'description' => 'The CHPP® Certification is the foundation level for analysts or Professionals in medical.',
      'href' => 'https://aapscm.com/chartered-healthcare-procurement-solutions-professional-chpp/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2023/12/CHPP.png',
    ),
    19 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/11/new-cousres1.png',
      'title' => 'American Certified Supply Chain Cybersecurity Professional (AC-SCCP)®',
      'description' => 'The Supply Chain Cybersecurity Professional Certification (AC-SCCP) is designed for professionals seeking practical, foundational….',
      'href' => 'https://aapscm.com/american-certified-supply-chain-cybersecurity-professional-ac-sccp/%20',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/1-19.png',
    ),
    20 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/11/new-cousres2.png',
      'title' => 'Chartered Advanced Supply Chain Cybersecurity Manager (CA-SCCM)®',
      'description' => 'The Advanced Supply Chain Cybersecurity Manager Certification (CA-SCCM) equips professionals with the expertise to protect ..',
      'href' => 'https://aapscm.com/chartered-advanced-supply-chain-cybersecurity-manager-ca-sccm/%20%20%20',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/2-5.png',
    ),
    21 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/12/10.png',
      'title' => 'Chartered AI-Driven Sustainable Procurement Manager (CAI-SPM)®',
      'description' => 'The AI-Driven Sustainable Procurement Manager Certification (CAI-SPM) is designed to empower professionals to lead the future….',
      'href' => 'https://aapscm.com/chartered-ai-driven-sustainable-procurement-manager-ca-ispm/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/3-2.png',
    ),
    22 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/11/new-cousres4.png',
      'title' => 'American Certified Blockchain for Supply Chain Professional ®',
      'description' => 'The Blockchain for Supply Chain Professional Certification (AC-BSCP) is designed for individuals and organizations ..',
      'href' => 'https://aapscm.com/american-certified-blockchain-for-supply-chain-professional-ac-bscp/%20',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/4-3.png',
    ),
    23 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/11/new-cousres5.png',
      'title' => 'Chartered Sustainable Supply Chain Manager (CSSCM)®',
      'description' => 'The Sustainable Supply Chain Management Certification (CSSCM) empowers professionals to design and manage eco…',
      'href' => 'https://aapscm.com/chartered-sustainable-supply-chain-manager-csscm/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/5-3.png',
    ),
    24 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/12/11.png',
      'title' => 'American Certified Digital Supply Chain Integration Professional (AC-DSCI)®',
      'description' => 'The American CertifiedDigital Supply Chain Integration Professional Certification (AC-DSCI) equips professionals..',
      'href' => 'https://aapscm.com/american-certified-digital-supply-chain-integration-professional-ac-dscip/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/6-4.png',
    ),
    25 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/11/new-cousres7.png',
      'title' => 'American Certified Global Supply Chain Risk and Resilience Professional(AC- GSRP)®',
      'description' => 'The Global Supply Chain Risk and Resilience Professional….',
      'href' => 'https://aapscm.com/american-certified-global-supply-chain-risk-and-resilience-professionalac-gsrp',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/11/7-3.png',
    ),
    26 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2024/12/1-9.png',
      'title' => 'Chartered Sustainable Culinary Tourism Manager (CSCTM®)',
      'description' => 'Take your career in culinary tourism to the next level with the Chartered Sustainable Culinary Tourism Manager (CSCTM®) certification!',
      'href' => 'https://aapscm.com/chartered-sustainable-culinary-tourism-manager-csctm/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2024/12/badge.png',
    ),
    27 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2025/01/1-45.png',
      'title' => 'Chartered Tourism Manager (CTM)®',
      'description' => 'Welcome to the Chartered Tourism Manager (CTM)® program, proudly offered by the ..',
      'href' => 'https://aapscm.com/ctm/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2025/01/1-46.png',
    ),
    28 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2025/01/1-47.png',
      'title' => 'American Certified E-Commerce Strategy and Growth Professional (AC-ESGP)®',
      'description' => 'The American Certified E-Commerce Strategy and Growth Professional (AC-ESGP)® certification is a comprehensive program …',
      'href' => 'https://aapscm.com/american-certified-e-commerce-strategy-and-growth-professional-ac-esgp/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2025/01/1-48.png',
    ),
    29 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2025/01/1-54.png',
      'title' => 'American Certified Ethical Practices & Sustainable E-Commerce Professional (AC-SEEP)®',
      'description' => 'The AC-SEEP® Certification is the industry-leading credential for professionals committed to building ethical, sustainable, and impactful…',
      'href' => 'https://aapscm.com/american-certified-ethical-practices-sustainable-e-commerce-professional-ac-seep/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2025/01/1-53.png',
    ),
    30 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2025/01/1-55.png',
      'title' => 'American Certified Digital Merchandising and User Experience Professional (AC-DMUX)®',
      'description' => 'The AC-DMUX® Certification is a premier credential designed to empower professionals with advanced Digital merchandising…',
      'href' => 'https://aapscm.com/american-certified-digital-merchandising-and-user-experience-professional-ac-dmux/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2025/01/1-56.png',
    ),
    31 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2025/01/1-50.png',
      'title' => 'Chartered E-Commerce Data Analytics and AI Professional (CED-AI)®',
      'description' => 'The Chartered E-Commerce Data Analytics and AI Professional (CED-AI)® certification is a cutting-edge credential designed. …',
      'href' => 'https://aapscm.com/chartered-e-commerce-data-analytics-and-ai-professional-ced-ai/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2025/01/1-49.png',
    ),
    32 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2025/01/1-51.png',
      'title' => 'Chartered Global Cross-Border E-Commerce Manager (CGCBE)®',
      'description' => 'The Chartered Global Cross-Border E-Commerce Manager (CGCBE)® certification is a world-class credential designed…',
      'href' => 'https://aapscm.com/chartered-global-cross-border-e-commerce-manager-cgcbe/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2025/01/1-52.png',
    ),
    33 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2025/01/1-39.png',
      'title' => 'American Certified Sustainable and Circular Supply Chain Professional (AC-CSCSP)®',
      'description' => 'The American Certified Sustainable and Circular Supply Chain Professional (AC-CSCSP)® certification is a pioneering program created by the….',
      'href' => 'https://aapscm.com/american-certified-sustainable-and-circular-supply-chain-professional-ac-cscsp/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2025/01/1-40.png',
    ),
    34 => 
    array (
      'image_top' => 'https://aapscm.com/wp-content/uploads/2025/01/1-41.png',
      'title' => 'American Certified Supply Chain Digital Transformation Manager (AC-SCDTM)®',
      'description' => 'The AmericanCertified Supply Chain Digital Transformation Manager (AC-SCDTM)® certification is a groundbreaking program designed by th……',
      'href' => 'https://aapscm.com/american-certified-supply-chain-digital-transformation-manager-ac-scdtm/',
      'image_bottom' => 'https://aapscm.com/wp-content/uploads/2025/01/1-42.png',
    ),
  ),
  'icon_boxes' => 
  array (
    0 => 
    array (
      'image' => 'https://aapscm.com/wp-content/uploads/2023/10/hand.png',
      'title' => 'Money back guarantee',
      'description' => 'included with all classes',
    ),
    1 => 
    array (
      'image' => 'https://aapscm.com/wp-content/uploads/2023/10/video-call.png',
      'title' => 'Attend live classes',
      'description' => 'from any web browser or connected device',
    ),
    2 => 
    array (
      'image' => 'https://aapscm.com/wp-content/uploads/2023/10/material.png',
      'title' => 'Includes class materials',
      'description' => 'from the American Association of procurement & supply chain management (AAPSCM)®, practice exam portal, 35 Contact Hours,',
    ),
    3 => 
    array (
      'image' => 'https://aapscm.com/wp-content/uploads/2023/10/email.png',
      'title' => 'Instant email confirmation',
      'description' => 'and class enrollment after checkout',
    ),
  ),
  'guarantee_items' => 
  array (
    0 => 
    array (
      'icon' => 'fas fa-check-circle',
      'text' => 'We guarantee that you will pass your AAPSCM exam after completing a Training Live Online Class with these simple requirements.',
    ),
    1 => 
    array (
      'icon' => 'fas fa-times-circle',
      'text' => 'If you do not pass the aapscm exam in three attempts, we will refund your entire class enrollment fee, provided all exam attempts occurred within 120 calendar days of your Training class concluding.',
    ),
    2 => 
    array (
      'icon' => 'fas fa-dot-circle',
      'text' => 'You must attend you aapscm certification class in full.',
    ),
    3 => 
    array (
      'icon' => 'fas fa-check-circle',
      'text' => 'You must complete all assigned practice exams and quizzes in your student portal and receive your Certificate of Completion (COC) prior to your first exam attempt',
    ),
  ),
);
