{{-- WordPress page content: board-of-directors-tracy-mckinnis --}}
<div class="wp-content">
<h3>Tracy McKinnis</h3>		
															<img width="206" height="206" src="https://aapscm.org/wp-content/uploads/2023/10/8-1.png" alt="" srcset="https://aapscm.org/wp-content/uploads/2023/10/8-1.png 206w, https://aapscm.org/wp-content/uploads/2023/10/8-1-150x150.png 150w, https://aapscm.org/wp-content/uploads/2023/10/8-1-100x100.png 100w" sizes="(max-width: 206px) 100vw, 206px" />															
			<h2>Tracy McKinnis</h2>		
			<h5>Chief Legal Officer & Marketing Director</h5>		
		<p>Tracy McKinnis is our Chief Legal Officer and Marketing Director. She is also the pioneer director and oversees all legal, risk and compliance, corporate governance, and governmental affairs matters for the association. Tracy is currently the President and CEO of Minimax Distribution LLC, located in the city and state of New York. She also held in-house legal leadership roles at Toll Brothers, IKON Office Solutions, and Aetna U.S. Healthcare. She began his career in private practice, specializing in securities and mergers and acquisitions. Tracy earned her law degree from the Harvard Law School, MA, and is a member of the bar in New York, Illinois, Maryland, New Jersey, and Washington, DC</p>
<p>She has experience as Business Development Executive, General Counsel &amp; Licensing Executive with large international corporate law firm experience, public company general counsel experience, and Fortune 500 corporate business experience. Specializing in sourcing, negotiating, and drafting strategic alliances, technology licenses, research collaborations, venture capital financings, intellectual property, mergers &amp; acquisitions, and IPOs in biotechnology, biofuels, pharmaceutical, telecom, IT, and software industries. Extensive experience with University Technology Transfer and leading international deals including deals in England, France, Germany, Switzerland, China, Holland, Brazil, Germany, Mexico, Canada, Australia, India, Denmark, Sweden, etc.</p>
</div>
